---
apiVersion: v1
kind: Service
metadata:
  name: kubernoodles
  namespace: demo
spec:
  ports:
    - port: 8000
      targetPort: 4000
  selector:
    app: kubernoodles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernoodles
  namespace: demo
spec:
  selector:
    matchLabels:
      app: kubernoodles
  replicas: 4
  template:
    metadata:
      labels:
        app: kubernoodles
    spec:
      containers:
      - name: kubernoodles-app
        image: bpschmitt/nodejs-logs-k8s:0.4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256M"
            cpu: "250m"
        ports:
        - containerPort: 4000
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: nrlicensekey
              key: nrlicensekey
        - name: NEW_RELIC_APP_NAME
          value: "Kubernoodles"